name: tawasul
description: "A new Flutter project."
publish_to: 'none' 
version: 0.1.4+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  image_picker: ^1.2.0
  cupertino_icons: ^1.0.8
  smooth_page_indicator: ^1.2.1
  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.14.4
  fl_chart: ^1.1.1
  sqflite: ^2.4.2
  path: ^1.9.1
  provider: ^6.1.5+1
  intl: ^0.20.2
  flutter_gemini: ^3.0.0
  http: ^1.6.0
  shared_preferences: ^2.5.3
  awesome_snackbar_content: ^0.1.8
  awesome_dialog: ^3.3.0
  flutter_dotenv: ^6.0.0

flutter_native_splash:
  color: "#151c22" 
  image: assets/images/icon2.png 
  android: true
  ios: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo2.png"
  min_sdk_android: 21 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
  fonts:
    - family: Pac
      fonts:
        - asset: assets/fonts/Pacifico.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter.ttf
    - family: Inter_ExtraBold
      fonts:
        - asset: assets/fonts/Inter_ExtraBold.ttf
    - family: Alex
      fonts:
        - asset: assets/fonts/Alexandria.ttf

